// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmdYikLaWrphJjFHmL_MAMFvgBFYEo21M',
    appId: '1:595302023121:web:b6a99410da823ececcaaf0',
    messagingSenderId: '595302023121',
    projectId: 'aarogyasaathi-bf8ba',
    authDomain: 'aarogyasaathi-bf8ba.firebaseapp.com',
    databaseURL: 'https://aarogyasaathi-bf8ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aarogyasaathi-bf8ba.appspot.com',
    measurementId: 'G-23KGK38995',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA13Q7F0lR0jmr8qUZ7VblpBbi3rMm5HRI',
    appId: '1:595302023121:android:4d55df61fd3e30e7ccaaf0',
    messagingSenderId: '595302023121',
    projectId: 'aarogyasaathi-bf8ba',
    databaseURL: 'https://aarogyasaathi-bf8ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aarogyasaathi-bf8ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWg5eLdlNnL8HNI8gaNee7Y3zn1Yqf3VM',
    appId: '1:595302023121:ios:7308ac4bafdabff0ccaaf0',
    messagingSenderId: '595302023121',
    projectId: 'aarogyasaathi-bf8ba',
    databaseURL: 'https://aarogyasaathi-bf8ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aarogyasaathi-bf8ba.appspot.com',
    iosBundleId: 'com.example.aarogyasaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmdYikLaWrphJjFHmL_MAMFvgBFYEo21M',
    appId: '1:595302023121:web:6213595381105771ccaaf0',
    messagingSenderId: '595302023121',
    projectId: 'aarogyasaathi-bf8ba',
    authDomain: 'aarogyasaathi-bf8ba.firebaseapp.com',
    databaseURL: 'https://aarogyasaathi-bf8ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aarogyasaathi-bf8ba.appspot.com',
    measurementId: 'G-DNEPEHG88L',
  );
 
}